//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesItem
    {
        public int Id { get; set; }
        public byte[] Image { get; set; }
        public int IdItem { get; set; }
    
        public virtual Items Items { get; set; }
    }
}
